version: '3.9'

services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    command: --replSet my-replica-set
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: --replSet my-replica-set
    ports:
      - 27018:27017
    networks:
      - mongo-network

  mongo3:
    image: mongo:6
    container_name: mongo3
    command: --replSet my-replica-set
    ports:
      - 27019:27017
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
